apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reeltimedeployment
  labels:
    app: reeltime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reeltime
  template:
    metadata:
      labels:
        app: reeltime
    spec:
      containers:
      - name: reeltime-container
        image: reeltimeregistry2.azurecr.io/reel-time-image:latest
        ports:
        - containerPort: 5000
        env:
          - name: "PASSWORD"
            value: Reeltime!
          - name: "DB"
            value: reel_time_db
          - name: "HOST"
            value: reel-time-db.chr9q1gt6nxw.us-east-1.rds.amazonaws.com
          - name: "USER"
            value: myadmin
      imagePullSecrets:
        - name: myregistrykey
